name: Draft & Publish Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --split-per-abi

      - name: Upload APKs to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/*-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Archive Windows Release
        shell: pwsh
        run: |
          Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath build\windows\x64\runner\vault_keeper_windows.zip

      - name: Upload Windows ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/windows/x64/runner/vault_keeper_windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
